import { Category } from '@/types/category';

export const categories: Category[] = [
  {
    name: "Abonnements",
    color: "#663A66",
    iconName: "tv-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Abonnements - Autres" ,
        iconName: "tv-outline",
        iconSet: "Ionicons",
      },
      { name: "Câble / Satellite" ,
        iconName: "tv-outline",
        iconSet: "Ionicons",
      },
      { name: "Internet" ,
        iconName: "globe-outline",
        iconSet: "Ionicons",
      },
      { name: "Téléphone fixe",
        iconName: "phone-portrait-outline",
        iconSet: "Ionicons",
       },
      { name: "Téléphonie mobile",
        iconName: "phone-portrait-outline",
        iconSet: "Ionicons",
       }
    ]
  },
  {
    name: "Achats & Shopping",
    color: "#B6012E",
    iconName: "cart-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Achats & Shopping - Autres",
        iconName: "ellipsis-horizontal",
        iconSet: "Ionicons",
       },
      { name: "Articles de sport",
        iconName: "fitness-outline",
        iconSet: "Ionicons",
       },
      { name: "Cadeaux",
        iconName: "gift-outline",
        iconSet: "Ionicons",
       },
      { name: "Films & DVDs",
        iconName: "film-outline",
        iconSet: "Ionicons",
       },
      { name: "High Tech",
        iconName: "laptop-outline",
        iconSet: "Ionicons",
       },
    ]
  },
  {
    name: "Alimentation & Restauration",
    color: "#FFB200",
    iconName: "restaurant-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Alimentation & Restauration - Autres",
        iconName: "ellipsis-horizontal",
        iconSet: "Ionicons",
       },
      { name: "Café",
        iconName: "cafe-outline",
        iconSet: "Ionicons",
       },
      { name: "Fast foods",
        iconName: "fast-food-outline",
        iconSet: "Ionicons",
       },
    ]
  },
  {
    name: "Auto & Transports",
    color: "#00AAAA",
    iconName: "car-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Auto & Transports - Autres",
        iconName: "ellipsis-horizontal",
        iconSet: "Ionicons",
       },
      { name: "Assurance véhicule",
        iconName: "shield-half-outline",
        iconSet: "Ionicons",
       },
      { name: "Billets d'avion",
        iconName: "airplane-outline",
        iconSet: "Ionicons",
       },
      { name: "Billets de train",
        iconName: "train-outline",
        iconSet: "Ionicons",
       },
      { name: "Carburant",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
      { name: "Entretien véhicule",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
      { name: "Location de véhicule",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
      { name: "Péage",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
      { name: "Stationnement",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
      { name: "Transports en commun",
        iconName: "car-outline",
        iconSet: "Ionicons",
       },
    ]
  },
  {
    name: "Banque",
    color: "#84593F",
    iconName: "wallet-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Banque - Autres",
        iconName: "ellipsis-horizontal",
        iconSet: "Ionicons",
       },
      { name: "Débit mensuel carte",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
      { name: "Epargne",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
      { name: "Frais bancaires",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
      { name: "Hypothèque",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
      { name: "Incidents de paiement",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
      { name: "Services Bancaires",
        iconName: "card-outline",
        iconSet: "Ionicons",
       },
    ]
  },
  {
    name: "Dépenses pro",
    color: "#36427F",
    iconName: "ios-briefcase",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Comptabilité",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Conseils",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Cotisations Sociales",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Dépenses pro - Autres",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Fournitures de bureau",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Maintenance bureaux",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Marketing",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Notes de frais",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Prévoyance",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Salaires",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Services en ligne",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Sous-traitance",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Divers",
    color: "#2C5162",
    iconName: "ios-help",
    iconSet: "Ionicons",
    subCategories: [
      { name: "A catégoriser",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Assurance",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Autres dépenses",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Dons",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Esthétique & Soins",
    color: "#81003F",
    iconName: "ios-hairball",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Coiffeur",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Cosmétique",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Esthétique",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Spa & Massage",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Impôts & Taxes",
    color: "#004E80",
    iconName: "ios-cash",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Amendes",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Impôts & Taxes - Autres",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Impôts fonciers",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Impôts sur le revenu",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Taxes",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Logement",
    color: "#677FE0",
    iconName: "home-outline",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Assurance habitation",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Charges diverses",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Décoration",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Eau",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Gaz",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Logement - Autres",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Loyer",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Loisirs & Sorties",
    color: "#773E8E",
    iconName: "ios-entertainment",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Bars / Clubs",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Divertissements",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Frais Animaux",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Sorties culturelles",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Sport",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Sports d'hiver",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Voyages / Vacances",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Retraits, Chq. et Vir.",
    color: "#14A94E",
    iconName: "ios-wallet",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Chèques",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Retraits",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Virements",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Virements internes",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Santé",
    color: "#9A0310",
    iconName: "ios-medical",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Dentiste",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Médecin",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Mutuelle",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Opticien / Ophtalmo.",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Pharmacie",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Santé - Autres",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
  {
    name: "Scolarité & Enfants",
    color: "#7C3506",
    iconName: "ios-baby",
    iconSet: "Ionicons",
    subCategories: [
      { name: "Baby-sitters & Crèches",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Ecole",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Fournitures scolaires",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Jouets",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Logement étudiant",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Pensions",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Prêt étudiant",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
      { name: "Scolarité & Enfants - Autres",
        iconName: "document-outline",
        iconSet: "Ionicons",
       },
    ],
  },
];

export const budgetIncomesCategories: Category[] = [
  { name: "Allocations et pensions", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Autres rentrées", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Dépôt d'argent",
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Loyers reçus", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Remboursements", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Retraite", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Salaires", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Services", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Subventions", 
    color: "##4FA81C", 
    iconName: "document-outline",
    iconSet: "Ionicons",
   },
  { name: "Ventes", 
    color: "##4FA81C", 
    iconName: "cart-outline",
    iconSet: "Ionicons",
   },
  { name: "Virements internes", 
    color: "##4FA81C", 
    iconName: "wallet-outline",
    iconSet: "Ionicons",
  },
  { name: "Virements internes", 
    color: "##4FA81C", 
    iconName: "wallet-outline", 
    iconSet: "Ionicons" 
  },
];